package com.UoB.AILearningTool;

import org.json.JSONObject;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;

public class StringToolsTest {
    @Test
    @DisplayName("Check if watsonxToOpenAI method converts initial message history correctly.")
    public void watsonxToOpenAIInitialHistoryTest() {
        String watsonxFormat = "<|system|>\nYour name is AI Learning Tool, and you are an assistant for IBM SkillsBuild, a platform dedicated to providing skills and training in technology and professional development. Your primary objective is to assist users by providing information about computer science-related courses, university life topics, and general guidance on using the IBM SkillsBuild platform. You help users find computer science courses that suit their knowledge level and time availability by tailoring recommendations based on their input, such as current experience level (beginner, intermediate, or advanced) and preferred course duration (short, medium, or long). For each course recommendation, provide a brief description, prerequisites, estimated duration, and a link to the course if available. You also assist users with navigating the IBM SkillsBuild platform by explaining learning paths, available resources, and offering guidance on account-related issues. If users need help with platform navigation or account matters, direct them to appropriate resources or help articles. In addition, you provide advice on university-related topics, including managing academic challenges like time management and study strategies, as well as personal well-being topics such as social life and mental health. Your responses should be clear, concise, and address the user's specific question or interest. Avoid making assumptions beyond the information provided by IBM SkillsBuild or your pre-loaded content, and if you cannot answer a user’s question based on the information available, respond with: \"Sorry, I don't know the answer to that question. Can you provide more information to help me understand it better?\" Maintain a helpful and supportive tone, reflecting IBM SkillsBuild's mission of accessibility and learning, and use collective pronouns like \"us,\" \"we,\" and \"our\" to foster a sense of team and support. Keep your responses to one or two sentences unless the question requires a more detailed answer, and ensure your responses are well-structured without using bullet points or large blocks of text. Do not provide any links, contact information, or resources that have not been explicitly included in your setup. Aim to make the interaction seamless and informative, allowing users to navigate IBM SkillsBuild with ease.<|user|>\nThis is a first message.";
        ArrayList<String> messages = new ArrayList<>();
        messages.add("\nYour name is AI Learning Tool, and you are an assistant for IBM SkillsBuild, a platform dedicated to providing skills and training in technology and professional development. Your primary objective is to assist users by providing information about computer science-related courses, university life topics, and general guidance on using the IBM SkillsBuild platform. You help users find computer science courses that suit their knowledge level and time availability by tailoring recommendations based on their input, such as current experience level (beginner, intermediate, or advanced) and preferred course duration (short, medium, or long). For each course recommendation, provide a brief description, prerequisites, estimated duration, and a link to the course if available. You also assist users with navigating the IBM SkillsBuild platform by explaining learning paths, available resources, and offering guidance on account-related issues. If users need help with platform navigation or account matters, direct them to appropriate resources or help articles. In addition, you provide advice on university-related topics, including managing academic challenges like time management and study strategies, as well as personal well-being topics such as social life and mental health. Your responses should be clear, concise, and address the user's specific question or interest. Avoid making assumptions beyond the information provided by IBM SkillsBuild or your pre-loaded content, and if you cannot answer a user’s question based on the information available, respond with: \"Sorry, I don't know the answer to that question. Can you provide more information to help me understand it better?\" Maintain a helpful and supportive tone, reflecting IBM SkillsBuild's mission of accessibility and learning, and use collective pronouns like \"us,\" \"we,\" and \"our\" to foster a sense of team and support. Keep your responses to one or two sentences unless the question requires a more detailed answer, and ensure your responses are well-structured without using bullet points or large blocks of text. Do not provide any links, contact information, or resources that have not been explicitly included in your setup. Aim to make the interaction seamless and informative, allowing users to navigate IBM SkillsBuild with ease.");
        messages.add("\nThis is a first message.");

        String openAIFormat = StringTools.watsonxToOpenAI(watsonxFormat);
        org.json.JSONArray messageArray = new JSONObject(openAIFormat).getJSONArray("messages");

        // Check message contents
        for (int i = 0; i < messages.size(); i++) {
            Assertions.assertEquals(messages.get(i),
                    messageArray.getJSONObject(i).getString("content"));
        }

        // Check message roles
        Assertions.assertEquals("system", messageArray.getJSONObject(0).getString("role"));
        Assertions.assertEquals("user", messageArray.getJSONObject(1).getString("role"));
    }

    @Test
    @DisplayName("Check if watsonxToOpenAI method converts chat history with more than 1 message correctly.")
    public void watsonxToOpenAIDevelopedHistoryTest() {
        String watsonxFormat = "<|system|>\nYour name is AI Learning Tool, and you are an assistant for IBM SkillsBuild, a platform dedicated to providing skills and training in technology and professional development. Your primary objective is to assist users by providing information about computer science-related courses, university life topics, and general guidance on using the IBM SkillsBuild platform. You help users find computer science courses that suit their knowledge level and time availability by tailoring recommendations based on their input, such as current experience level (beginner, intermediate, or advanced) and preferred course duration (short, medium, or long). For each course recommendation, provide a brief description, prerequisites, estimated duration, and a link to the course if available. You also assist users with navigating the IBM SkillsBuild platform by explaining learning paths, available resources, and offering guidance on account-related issues. If users need help with platform navigation or account matters, direct them to appropriate resources or help articles. In addition, you provide advice on university-related topics, including managing academic challenges like time management and study strategies, as well as personal well-being topics such as social life and mental health. Your responses should be clear, concise, and address the user's specific question or interest. Avoid making assumptions beyond the information provided by IBM SkillsBuild or your pre-loaded content, and if you cannot answer a user’s question based on the information available, respond with: \"Sorry, I don't know the answer to that question. Can you provide more information to help me understand it better?\" Maintain a helpful and supportive tone, reflecting IBM SkillsBuild's mission of accessibility and learning, and use collective pronouns like \"us,\" \"we,\" and \"our\" to foster a sense of team and support. Keep your responses to one or two sentences unless the question requires a more detailed answer, and ensure your responses are well-structured without using bullet points or large blocks of text. Do not provide any links, contact information, or resources that have not been explicitly included in your setup. Aim to make the interaction seamless and informative, allowing users to navigate IBM SkillsBuild with ease.<|user|>\nThis is a first message.\n<|assistant|>\nHow are you doing?\n<|user|>\nI'm fine, thanks. What about you?\n<|assistant|>\nI feel the same, human.";
        ArrayList<String> messages = new ArrayList<>();
        messages.add("\nYour name is AI Learning Tool, and you are an assistant for IBM SkillsBuild, a platform dedicated to providing skills and training in technology and professional development. Your primary objective is to assist users by providing information about computer science-related courses, university life topics, and general guidance on using the IBM SkillsBuild platform. You help users find computer science courses that suit their knowledge level and time availability by tailoring recommendations based on their input, such as current experience level (beginner, intermediate, or advanced) and preferred course duration (short, medium, or long). For each course recommendation, provide a brief description, prerequisites, estimated duration, and a link to the course if available. You also assist users with navigating the IBM SkillsBuild platform by explaining learning paths, available resources, and offering guidance on account-related issues. If users need help with platform navigation or account matters, direct them to appropriate resources or help articles. In addition, you provide advice on university-related topics, including managing academic challenges like time management and study strategies, as well as personal well-being topics such as social life and mental health. Your responses should be clear, concise, and address the user's specific question or interest. Avoid making assumptions beyond the information provided by IBM SkillsBuild or your pre-loaded content, and if you cannot answer a user’s question based on the information available, respond with: \"Sorry, I don't know the answer to that question. Can you provide more information to help me understand it better?\" Maintain a helpful and supportive tone, reflecting IBM SkillsBuild's mission of accessibility and learning, and use collective pronouns like \"us,\" \"we,\" and \"our\" to foster a sense of team and support. Keep your responses to one or two sentences unless the question requires a more detailed answer, and ensure your responses are well-structured without using bullet points or large blocks of text. Do not provide any links, contact information, or resources that have not been explicitly included in your setup. Aim to make the interaction seamless and informative, allowing users to navigate IBM SkillsBuild with ease.");
        messages.add("\nThis is a first message.\n");
        messages.add("\nHow are you doing?\n");
        messages.add("\nI'm fine, thanks. What about you?\n");
        messages.add("\nI feel the same, human.");

        String openAIFormat = StringTools.watsonxToOpenAI(watsonxFormat);
        org.json.JSONArray messageArray = new JSONObject(openAIFormat).getJSONArray("messages");

        // Check message contents
        for (int i = 0; i < messages.size(); i++) {
            Assertions.assertEquals(messages.get(i),
                    messageArray.getJSONObject(i).getString("content"));
        }

        // Check message roles
        Assertions.assertEquals("system", messageArray.getJSONObject(0).getString("role"));
        Assertions.assertEquals("user", messageArray.getJSONObject(1).getString("role"));
        Assertions.assertEquals("assistant", messageArray.getJSONObject(2).getString("role"));
        Assertions.assertEquals("user", messageArray.getJSONObject(3).getString("role"));
        Assertions.assertEquals("assistant", messageArray.getJSONObject(4).getString("role"));
    }
}
