# Push the Docker image to GHCR and deploy on the server
name: CD Deployment

on:
  push:
    branches:
      - dev
      - feature/issue-203/fix-CD-runner
      - bugfix/issue-232/implement-openai-secret

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      BACKEND_URL: ailearningtool.ddns.net
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Java 21
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'  
          distribution: 'temurin'

      # Step 3: Adjust OpenAI API key.
      - name: Adjust the OpenAI API key
        run: (envsubst < OpenAIAuthenticator.java) > OpenAIAuthenticatorUPD.java && cp OpenAIAuthenticatorUPD.java OpenAIAuthenticator.java && rm OpenAIAuthenticatorUPD.java
        working-directory: backend/src/main/java/com/UoB/AILearningTool

      # Step 4: Adjust the backend application parameters
      - name: Adjust the backend URL
        run: | 
          echo -e "spring.application.name=AILearningTool\n\
          server.port=443\n\
          spring.servlet.multipart.max-file-size=50MB\n\
          spring.servlet.multipart.max-request-size=50MB\n\
          spring.web.resources.static-locations=classpath:/static/\n\
          server.servlet.encoding.charset=UTF-8\n\
          server.servlet.encoding.enabled=true\n\
          server.servlet.encoding.force=true\n\
          server.ssl.key-store=./file:keystore.p12\n\
          server.ssl.key-store-password=ailearntool" > application.properties
        working-directory: backend/src/main/resources

      # Step 5: Adjust the frontend BACKEND_URL constant
      - name: Update frontend BACKEND_URL constant
        run : echo "const BACKEND_URL = 'http://$BACKEND_URL';
              export { BACKEND_URL };" > globalConstants.js
        working-directory: frontend/src/assets
        
      # Step 6: Build the JAR file with Maven
      - name: Build JAR
        run: mvn clean package
        working-directory: backend

      # Step 7: Log in to GitHub Container Registry
      - name: Log in to GHCR
        run: echo "${{ secrets.CONTAINER_REGISTRY_PAT }}" | docker login ghcr.io -u GerardChabaBristol --password-stdin

      # Step 8: Build and push the Docker image
      - name: Publish Docker image to GHCR
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/spe-uob/2024-ailearningtool:latest

      # Step 9: Pull the image and deploy on the server
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ghcr.io/spe-uob/2024-ailearningtool:latest
            docker stop ailearningtool || true
            docker rm ailearningtool || true
            sudo docker run -d --name ailearningtool -p 443:443 ghcr.io/spe-uob/2024-ailearningtool:latest -v /keystore.p12:/keystore.p12

